"""empty message

Revision ID: 0666333c4d3c
Revises: 97384fe2d5b4
Create Date: 2024-12-31 19:05:50.313363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0666333c4d3c'
down_revision: Union[str, None] = '97384fe2d5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_COLLABO_APPROVE_colab_id_fkey', 'TBL_COLLABO_APPROVE', type_='foreignkey')
    op.drop_column('TBL_COLLABO_APPROVE', 'colab_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_COLLABO_APPROVE', sa.Column('colab_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('TBL_COLLABO_APPROVE_colab_id_fkey', 'TBL_COLLABO_APPROVE', 'TBL_COLLABO', ['colab_id'], ['collabo_id'])
    # ### end Alembic commands ###
