"""empty message

Revision ID: 0df896ca7ea9
Revises: 5be72b6f94ea
Create Date: 2024-12-10 10:47:49.694520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df896ca7ea9'
down_revision: Union[str, None] = '5be72b6f94ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'TBL_CREATOR', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_CREATOR', type_='unique')
    # ### end Alembic commands ###
