"""empty message

Revision ID: 135a62452878
Revises: 4be6070d5df3
Create Date: 2024-12-21 00:12:23.812706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135a62452878'
down_revision: Union[str, None] = '4be6070d5df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_COLLABO', sa.Column('title', sa.String(length=64), nullable=False))
    op.add_column('TBL_COLLABO', sa.Column('description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TBL_COLLABO', 'description')
    op.drop_column('TBL_COLLABO', 'title')
    # ### end Alembic commands ###
