"""empty message

Revision ID: 48c8c9f3e2c3
Revises: 08f8e6d22b63
Create Date: 2024-09-28 16:20:17.613089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c8c9f3e2c3'
down_revision: Union[str, None] = '08f8e6d22b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_CREATOR_product_id_fkey', 'TBL_CREATOR', type_='foreignkey')
    op.drop_column('TBL_CREATOR', 'product_id')
    op.drop_constraint('TBL_CREATOR_PRODUCT_creator_id_fkey', 'TBL_CREATOR_PRODUCT', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_CREATOR_PRODUCT', 'TBL_CREATOR', ['creator_id'], ['creator_id'])
    op.alter_column('TBL_USER', 'user_screen_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TBL_USER', 'user_screen_id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'TBL_CREATOR_PRODUCT', type_='foreignkey')
    op.create_foreign_key('TBL_CREATOR_PRODUCT_creator_id_fkey', 'TBL_CREATOR_PRODUCT', 'TBL_USER', ['creator_id'], ['user_id'])
    op.add_column('TBL_CREATOR', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('TBL_CREATOR_product_id_fkey', 'TBL_CREATOR', 'TBL_PRODUCT', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
