"""empty message

Revision ID: 4f831c1db811
Revises: 72d96bef66e1
Create Date: 2025-02-18 16:26:05.201269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f831c1db811'
down_revision: Union[str, None] = '72d96bef66e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_COLAB_WANT',
    sa.Column('colab_want_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_creator_id', sa.UUID(), nullable=False),
    sa.Column('receive_creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['receive_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.ForeignKeyConstraint(['sender_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.PrimaryKeyConstraint('colab_want_id')
    )
    op.add_column('TBL_NOTIFICATION', sa.Column('collabo_want_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'TBL_NOTIFICATION', 'TBL_COLAB_WANT', ['collabo_want_id'], ['colab_want_id'])
    # ### end Alembic commands ###
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" DROP CONSTRAINT check_notification_children
    """)
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" ADD CONSTRAINT check_notification_children CHECK (
        (CASE WHEN "collabo_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_request_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_approve_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_want_id" IS NULL THEN 0 ELSE 1 END)
        = 1
    )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_NOTIFICATION', type_='foreignkey')
    op.drop_column('TBL_NOTIFICATION', 'collabo_want_id')
    op.drop_table('TBL_COLAB_WANT')
    # ### end Alembic commands ###
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" DROP CONSTRAINT check_notification_children
    """)
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" ADD CONSTRAINT check_notification_children CHECK (
        (CASE WHEN "collabo_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_request_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_approve_id" IS NULL THEN 0 ELSE 1 END)
        = 1
    )
    """)
