"""empty message

Revision ID: 53b910b5dcee
Revises: 64ff91ffb65c, a8eaaf51d9cd
Create Date: 2024-12-01 21:02:07.144896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b910b5dcee'
down_revision: Union[str, None] = ('64ff91ffb65c', 'a8eaaf51d9cd')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('recruit_id', sa.UUID(), nullable=False))
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_column('TBL_CREATOR_RECRUIT', 'context')
    op.drop_column('TBL_CREATOR_RECRUIT', 'creator_recruit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('creator_recruit_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('context', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('TBL_CREATOR_RECRUIT', 'description')
    op.drop_column('TBL_CREATOR_RECRUIT', 'recruit_id')
    # ### end Alembic commands ###
