"""empty message

Revision ID: 5db3890c939b
Revises: bb5aafef3135
Create Date: 2024-12-07 21:46:43.888476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5db3890c939b'
down_revision: Union[str, None] = 'bb5aafef3135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_NOTIFICATION_COLLABO', sa.Column('receive_creator_id', sa.UUID(), nullable=False))
    op.drop_constraint('TBL_NOTIFICATION_COLLABO_sent_creator_id_fkey', 'TBL_NOTIFICATION_COLLABO', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_NOTIFICATION_COLLABO', 'TBL_CREATOR', ['receive_creator_id'], ['creator_id'])
    op.drop_column('TBL_NOTIFICATION_COLLABO', 'sent_creator_id')
    op.alter_column('TBL_PRODUCT', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TBL_PRODUCT', 'purchase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('TBL_NOTIFICATION_COLLABO', sa.Column('sent_creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TBL_NOTIFICATION_COLLABO', type_='foreignkey')
    op.create_foreign_key('TBL_NOTIFICATION_COLLABO_sent_creator_id_fkey', 'TBL_NOTIFICATION_COLLABO', 'TBL_CREATOR', ['sent_creator_id'], ['creator_id'])
    op.drop_column('TBL_NOTIFICATION_COLLABO', 'receive_creator_id')
    # ### end Alembic commands ###
