"""empty message

Revision ID: 5f8f448de760
Revises: 82c0f5b58ba5
Create Date: 2025-01-27 13:46:52.429124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f448de760'
down_revision: Union[str, None] = '82c0f5b58ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_RECRUIT', sa.Column('post_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TBL_RECRUIT', 'post_date')
    # ### end Alembic commands ###
