"""empty message

Revision ID: 68b2f77dee9f
Revises: 0df896ca7ea9
Create Date: 2024-12-10 22:18:07.536796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b2f77dee9f'
down_revision: Union[str, None] = '0df896ca7ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_COLLABO_REQUEST',
    sa.Column('collabo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_creator_id', sa.UUID(), nullable=False),
    sa.Column('receive_creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['receive_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.ForeignKeyConstraint(['sender_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.PrimaryKeyConstraint('collabo_id')
    )
    op.create_table('TBL_COLLABO_CREATOR',
    sa.Column('collabo_creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collabo_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collabo_id'], ['TBL_COLLABO.collabo_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.PrimaryKeyConstraint('collabo_creator_id')
    )
    op.add_column('TBL_COLLABO', sa.Column('owner_creator_id', sa.Uuid(), nullable=False))
    op.drop_constraint('TBL_COLLABO_sender_creator_id_fkey', 'TBL_COLLABO', type_='foreignkey')
    op.drop_constraint('TBL_COLLABO_receive_creator_id_fkey', 'TBL_COLLABO', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_COLLABO', 'TBL_CREATOR', ['owner_creator_id'], ['creator_id'])
    op.drop_column('TBL_COLLABO', 'sender_creator_id')
    op.drop_column('TBL_COLLABO', 'receive_creator_id')
    op.drop_constraint('TBL_COLLABO_APPROVE_collabo_id_fkey', 'TBL_COLLABO_APPROVE', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_COLLABO_APPROVE', 'TBL_COLLABO_REQUEST', ['collabo_id'], ['collabo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_COLLABO_APPROVE', type_='foreignkey')
    op.create_foreign_key('TBL_COLLABO_APPROVE_collabo_id_fkey', 'TBL_COLLABO_APPROVE', 'TBL_COLLABO', ['collabo_id'], ['collabo_id'])
    op.add_column('TBL_COLLABO', sa.Column('receive_creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('TBL_COLLABO', sa.Column('sender_creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TBL_COLLABO', type_='foreignkey')
    op.create_foreign_key('TBL_COLLABO_receive_creator_id_fkey', 'TBL_COLLABO', 'TBL_CREATOR', ['receive_creator_id'], ['creator_id'])
    op.create_foreign_key('TBL_COLLABO_sender_creator_id_fkey', 'TBL_COLLABO', 'TBL_CREATOR', ['sender_creator_id'], ['creator_id'])
    op.drop_column('TBL_COLLABO', 'owner_creator_id')
    op.drop_table('TBL_COLLABO_CREATOR')
    op.drop_table('TBL_COLLABO_REQUEST')
    # ### end Alembic commands ###
