"""empty message

Revision ID: 73107bce336e
Revises: 2b00b9c850d2
Create Date: 2024-11-05 14:10:24.613965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73107bce336e'
down_revision: Union[str, None] = '2b00b9c850d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TBL_CART_PRODUCT', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TBL_CART_PRODUCT', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
