"""empty message

Revision ID: 7402e6c7d71e
Revises: 9544350e3020
Create Date: 2024-11-06 15:53:46.669127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7402e6c7d71e'
down_revision: Union[str, None] = '9544350e3020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_CHAT',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('TBL_CHAT_MESSAGE',
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['TBL_CHAT.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_message_id')
    )
    op.create_table('TBL_CHAT_USER',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['TBL_CHAT.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['TBL_USER.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('TBL_CHAT_IMAGE',
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('image_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['TBL_CHAT_MESSAGE.chat_message_id'], ),
    sa.PrimaryKeyConstraint('chat_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBL_CHAT_IMAGE')
    op.drop_table('TBL_CHAT_USER')
    op.drop_table('TBL_CHAT_MESSAGE')
    op.drop_table('TBL_CHAT')
    # ### end Alembic commands ###
