"""empty message

Revision ID: 773cc64e7a1f
Revises: 08f8e6d22b63
Create Date: 2024-09-19 15:17:12.630670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773cc64e7a1f'
down_revision: Union[str, None] = '08f8e6d22b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_CREATOR_PRODUCT_creator_id_fkey', 'TBL_CREATOR_PRODUCT', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_CREATOR_PRODUCT', 'TBL_CREATOR', ['creator_id'], ['creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_CREATOR_PRODUCT', type_='foreignkey')
    op.create_foreign_key('TBL_CREATOR_PRODUCT_creator_id_fkey', 'TBL_CREATOR_PRODUCT', 'TBL_USER', ['creator_id'], ['user_id'])
    # ### end Alembic commands ###
