"""empty message

Revision ID: 82c0f5b58ba5
Revises: a091b50c8efa
Create Date: 2025-01-01 22:18:02.918373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c0f5b58ba5'
down_revision: Union[str, None] = 'a091b50c8efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    TRUNCATE "TBL_COLLABO_APPROVE" CASCADE
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'TBL_COLLABO_APPROVE', ['colab_creator_id'])
    op.create_unique_constraint(None, 'TBL_COLLABO_CREATOR', ['collabo_id', 'creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_COLLABO_CREATOR', type_='unique')
    op.drop_constraint(None, 'TBL_COLLABO_APPROVE', type_='unique')
    # ### end Alembic commands ###
