"""empty message

Revision ID: 84fb81c4db70
Revises: 773cc64e7a1f
Create Date: 2024-09-19 16:24:23.483233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fb81c4db70'
down_revision: Union[str, None] = '773cc64e7a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_CREATOR_product_id_fkey', 'TBL_CREATOR', type_='foreignkey')
    op.drop_column('TBL_CREATOR', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('TBL_CREATOR_product_id_fkey', 'TBL_CREATOR', 'TBL_PRODUCT', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
