"""empty message

Revision ID: 9544350e3020
Revises: 48c8c9f3e2c3
Create Date: 2024-10-16 21:41:18.732959

"""
from typing import Sequence, Union

import sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9544350e3020'
down_revision: Union[str, None] = '48c8c9f3e2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_USER_FOLLOW',
                    sa.Column('follow_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('creator_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['TBL_CREATOR.creator_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['TBL_USER.user_id'], ),
                    sa.PrimaryKeyConstraint('follow_id')
                    )
    op.drop_column('TBL_PRODUCT', 'product_price')
    op.add_column('TBL_PRODUCT',
                  sqlalchemy.Column("product_price", sqlalchemy.Integer, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TBL_PRODUCT', 'product_price',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=False)
    op.drop_table('TBL_USER_FOLLOW')
    # ### end Alembic commands ###
