"""empty message

Revision ID: 9d3faf8b71bb
Revises: db587f701a6d
Create Date: 2024-09-06 13:46:25.773729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3faf8b71bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_USER',
    sa.Column('user_id', sa.String(length=64), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('user_screen_id', sa.String(length=64), nullable=False),
    sa.Column('user_icon_uuid', sa.String(length=36), nullable=True),
    sa.Column('user_date', sa.DateTime(), nullable=True),
    sa.Column('user_mail', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBL_USER')
    # ### end Alembic commands ###
