"""empty message

Revision ID: a091b50c8efa
Revises: 0666333c4d3c
Create Date: 2025-01-01 17:35:02.214068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a091b50c8efa'
down_revision: Union[str, None] = '0666333c4d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_NOTIFICATION_collabo_approve_id_fkey', 'TBL_NOTIFICATION', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_NOTIFICATION', 'TBL_COLLABO_APPROVE', ['collabo_approve_id'], ['collabo_approve_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TBL_NOTIFICATION', type_='foreignkey')
    op.create_foreign_key('TBL_NOTIFICATION_collabo_approve_id_fkey', 'TBL_NOTIFICATION', 'TBL_COLLABO', ['collabo_approve_id'], ['collabo_id'])
    # ### end Alembic commands ###
