"""empty message

Revision ID: a8eaaf51d9cd
Revises: 22661e1abfd2, cac1fe43e0ae
Create Date: 2024-12-01 20:57:02.769950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eaaf51d9cd'
down_revision: Union[str, None] = ('22661e1abfd2', 'cac1fe43e0ae')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_CART',
                    sa.Column('cart_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('purchase_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['TBL_USER.user_id'], ),
                    sa.PrimaryKeyConstraint('cart_id')
                    )
    op.create_table('TBL_CART_PRODUCT',
                    sa.Column('cart_id', sa.UUID(), nullable=False),
                    sa.Column('product_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['cart_id'], ['TBL_CART.cart_id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['TBL_PRODUCT.product_id'], ),
                    sa.PrimaryKeyConstraint('cart_id', 'product_id')
                    )
    op.drop_column('TBL_CREATOR_RECRUIT', 'contact_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('contact_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_table('TBL_CART_PRODUCT')
    op.drop_table('TBL_CART')
    # ### end Alembic commands ###
