"""empty message

Revision ID: bb5aafef3135
Revises: 53b910b5dcee
Create Date: 2024-12-04 13:50:53.143607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5aafef3135'
down_revision: Union[str, None] = '53b910b5dcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_RECRUIT',
    sa.Column('recruit_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.PrimaryKeyConstraint('recruit_id')
    )
    op.drop_table('TBL_CREATOR_RECRUIT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_CREATOR_RECRUIT',
    sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('recruit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['TBL_CREATOR.creator_id'], name='TBL_CREATOR_RECRUIT_creator_id_fkey')
    )
    op.drop_table('TBL_RECRUIT')
    # ### end Alembic commands ###
