"""empty message

Revision ID: d4ccfe3dc8b6
Revises: 2519a0e70d14
Create Date: 2024-12-08 20:20:47.963899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ccfe3dc8b6'
down_revision: Union[str, None] = '2519a0e70d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_COLLABO_NOTIFICATION',
    sa.Column('notification_collabo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('sender_creator_id', sa.UUID(), nullable=False),
    sa.Column('receive_creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['TBL_NOTIFICATION.notification_id'], ),
    sa.ForeignKeyConstraint(['receive_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.ForeignKeyConstraint(['sender_creator_id'], ['TBL_CREATOR.creator_id'], ),
    sa.PrimaryKeyConstraint('notification_collabo_id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_table('TBL_APPROVE_NOTIFICATION',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('collabo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collabo_id'], ['TBL_COLLABO_NOTIFICATION.notification_collabo_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['TBL_NOTIFICATION.notification_id'], ),
    sa.PrimaryKeyConstraint('id', 'notification_id')
    )
    op.drop_table('TBL_NOTIFICATION_COLLABO')
    op.add_column('TBL_NOTIFICATION', sa.Column('read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TBL_NOTIFICATION', 'read')
    op.create_table('TBL_NOTIFICATION_COLLABO',
    sa.Column('notification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receive_creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['TBL_NOTIFICATION.notification_id'], name='TBL_NOTIFICATION_COLLABO_notification_id_fkey'),
    sa.ForeignKeyConstraint(['receive_creator_id'], ['TBL_CREATOR.creator_id'], name='TBL_NOTIFICATION_COLLABO_receive_creator_id_fkey'),
    sa.ForeignKeyConstraint(['sender_creator_id'], ['TBL_CREATOR.creator_id'], name='TBL_NOTIFICATION_COLLABO_sender_creator_id_fkey'),
    sa.PrimaryKeyConstraint('notification_id', name='TBL_NOTIFICATION_COLLABO_pkey')
    )
    op.drop_table('TBL_APPROVE_NOTIFICATION')
    op.drop_table('TBL_COLLABO_NOTIFICATION')
    # ### end Alembic commands ###
