"""empty message

Revision ID: dfc2d2840dfa
Revises: cac1fe43e0ae
Create Date: 2024-12-01 20:28:00.659982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc2d2840dfa'
down_revision: Union[str, None] = 'cac1fe43e0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TBL_CREATOR_RECRUIT', 'contact_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('contact_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
