"""empty message

Revision ID: e2c490255a16
Revises: 32d98e7c724b
Create Date: 2025-02-25 15:51:01.919727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c490255a16'
down_revision: Union[str, None] = '32d98e7c724b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_CHAT_MESSAGE_index_key', 'TBL_CHAT_MESSAGE', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('TBL_CHAT_MESSAGE_index_key', 'TBL_CHAT_MESSAGE', ['index'])
    # ### end Alembic commands ###
