"""empty message

Revision ID: f0d4fe9dade3
Revises: 68b2f77dee9f
Create Date: 2024-12-19 12:15:20.849093

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f0d4fe9dade3'
down_revision: Union[str, None] = '68b2f77dee9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TBL_COLLABO_APPROVE_collabo_id_fkey', 'TBL_COLLABO_APPROVE', type_='foreignkey')
    op.drop_column('TBL_COLLABO_REQUEST', 'collabo_id')
    op.add_column('TBL_COLLABO_REQUEST',
                  sa.Column('collabo_request_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_primary_key("TBL_COLLABO_REQUEST_pkey", "TBL_COLLABO_REQUEST", ["collabo_request_id"])
    op.create_foreign_key(None, 'TBL_COLLABO_APPROVE', 'TBL_COLLABO_REQUEST', ['collabo_id'], ['collabo_request_id'])
    op.add_column('TBL_NOTIFICATION', sa.Column('collabo_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'TBL_NOTIFICATION', 'TBL_COLLABO_REQUEST', ['collabo_request_id'],
                          ['collabo_request_id'])
    # ### end Alembic commands ###
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" DROP CONSTRAINT check_notification_children
    """)
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" ADD CONSTRAINT check_notification_children CHECK (
        (CASE WHEN "collabo_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_approve_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_request_id" IS NULL THEN 0 ELSE 1 END)
        = 1
    )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TBL_NOTIFICATION', 'collabo_request_id')
    op.add_column('TBL_COLLABO_REQUEST', sa.Column('collabo_id', sa.UUID(), autoincrement=False, nullable=False))
    op.execute("""alter table "TBL_COLLABO_APPROVE"
    drop constraint "TBL_COLLABO_APPROVE_collabo_id_fkey" cascade;""")
    op.execute("""alter table "TBL_NOTIFICATION"
    drop constraint "TBL_NOTIFICATION_pkey" cascade;""")
    op.execute("""alter table "TBL_COLLABO_REQUEST"
    drop constraint "TBL_COLLABO_REQUEST_pkey" cascade;""")
    op.drop_column('TBL_COLLABO_REQUEST', 'collabo_request_id')
    op.create_primary_key("TBL_COLLABO_REQUEST_pkey", "TBL_COLLABO_REQUEST", ["collabo_id"])
    op.create_foreign_key('TBL_COLLABO_APPROVE_collabo_id_fkey', 'TBL_COLLABO_APPROVE', 'TBL_COLLABO_REQUEST',
                          ['collabo_id'], ['collabo_id'])
    # ### end Alembic commands ###
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" DROP CONSTRAINT check_notification_children
    """)
    op.execute("""
    ALTER TABLE "TBL_NOTIFICATION" ADD CONSTRAINT check_notification_children CHECK (
        (CASE WHEN "collabo_id" IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN "collabo_approve_id" IS NULL THEN 0 ELSE 1 END)
        = 1
    )
    """)
