"""empty message

Revision ID: fbbc55eae24c
Revises: 84fb81c4db70
Create Date: 2024-09-20 02:15:33.663074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbc55eae24c'
down_revision: Union[str, None] = '84fb81c4db70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('recruiting_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('recruiting_creator_id', sa.UUID(), nullable=False))
    op.drop_constraint('TBL_CREATOR_RECRUIT_creator_id_fkey', 'TBL_CREATOR_RECRUIT', type_='foreignkey')
    op.create_foreign_key(None, 'TBL_CREATOR_RECRUIT', 'TBL_CREATOR', ['recruiting_creator_id'], ['creator_id'])
    op.drop_column('TBL_CREATOR_RECRUIT', 'creator_recruit_id')
    op.drop_column('TBL_CREATOR_RECRUIT', 'contact_address')
    op.drop_column('TBL_CREATOR_RECRUIT', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('contact_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('TBL_CREATOR_RECRUIT', sa.Column('creator_recruit_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TBL_CREATOR_RECRUIT', type_='foreignkey')
    op.create_foreign_key('TBL_CREATOR_RECRUIT_creator_id_fkey', 'TBL_CREATOR_RECRUIT', 'TBL_CREATOR', ['creator_id'], ['creator_id'])
    op.drop_column('TBL_CREATOR_RECRUIT', 'recruiting_creator_id')
    op.drop_column('TBL_CREATOR_RECRUIT', 'recruiting_id')
    # ### end Alembic commands ###
