name: cd

on:
  push:
    branches:
      - "develop"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.openapi.yml up openapi-generator
      # argo
      - name: checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.conf.repository }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/${{ matrix.conf.name }}:${{ github.ref_name }}-${{ github.sha }}"' \
          ${{ matrix.conf.manifestFile }}

      - name: push
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)" && \
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)" && \
          git add -u && \
          git add . && \
          (git commit -m "client generated" || true) && \
          git push