on:
  push:
jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.openapi.yml up openapi-generator

      - name: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
