name: test

on: [ push ]

jobs:
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: ./temp
          key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
          restore-keys: |
            ${{ github.ref }}
            refs/head/develop
      - run:
          mkdir -p temp/test/app-data
          mkdir -p temp/test/db-data
      - run: docker compose -f docker-compose.test.yml up backend-test --exit-code-from backend-test
      - run: docker compose -f docker-compose.test.yml logs
        if: always()
